import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pl"
      className={`${albertSans.variable} text-lg font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col h-full font-sans">
        {children}
      </body>
    </html>
  );
}
