import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import AppBar from "./components/app-bar/app-bar";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pl"
      className={`${albertSans.variable} xl:text-lg lg:text-base md:text-sm text-xs font-sans h-full antialiased`}
    >
      <body className="min-h-full flex flex-col h-full font-sans items-center">
        {children}
        <AppBar />
      </body>
    </html>
  );
}
